swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://aircraft-list-37b64nc45a-uc.a.run.app
paths:
  /airspace/aircraft/list:
    get:
      summary: aircraft-list
      operationId: aircraft-list
      responses:
        '200':
          description: OK
          schema:
            type: string
