swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: ${aircraft_info_url}
paths:
  /airspace/aircraft/{icao24}/info:
    get:
      parameters:
        - in: path
          name: icao24
          type: string
          required: true
          description: Icao24 of the aircraft.
      summary: aircraft-info
      operationId: aircraft-info
      responses:
        '200':
          description: OK
          schema:
            type: string
