services:
  jobmanager:
    image: flink:1.14.4-scala_2.12
    ports:
      - "8081:8081"
    expose:
      - 5555
    command: standalone-job --job-classname it.unibo.states_source.Main
    volumes:
      - ./target:/opt/flink/usrlib
      - ./:/usr/local/flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 1        

  taskmanager:
    image: flink:1.14.4-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./target:/opt/flink/usrlib
      - ./:/usr/local/flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 1 