name: Code analysis
on: 
  pull_request:
    branches:
      - 'main'
      - 'test_deploy'
  push:
    branches:
      - 'develop'
      - 'test_develop'
      - 'main'
      - 'test_deploy'
env:
  FINDSECBUGS_VERSION: 1.12.0
jobs:
  codeql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'go']
    steps:
      - run: echo "A ${{ github.event_name }} event happened, starting workflow."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - run: echo "Job ended."

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep scan --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/r
            p/security-audit
            p/secrets
            p/ci
            p/javascript
            p/scala
            p/golang
            p/owasp-top-ten
            p/clientside-js
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

  identify_java_scala:
    uses: ./.github/workflows/identify_java_scala.yaml

  findsecbugs:
    runs-on: ubuntu-latest
    needs: identify_java_scala
    strategy:
      fail-fast: false
      matrix:
        pom: ${{ fromJson(needs.identify_java_scala.outputs.directories) }}
    steps:
    # we use OpenSky API, so we need to compile the dependency to package our files
    - run: git clone https://github.com/openskynetwork/opensky-api.git
    - run: mvn -f ./opensky-api/java/pom.xml install
    # code scan
    - uses: actions/checkout@v3
    - run: mvn -f ".${{ matrix.pom }}/pom.xml" package
    - run: wget https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-${FINDSECBUGS_VERSION}/findsecbugs-cli-${FINDSECBUGS_VERSION}.zip
    - run: unzip findsecbugs-cli-${FINDSECBUGS_VERSION}
    - run: chmod u+x ./findsecbugs.sh
    - name: Run FindSecBugs checks
      run: ./findsecbugs.sh -sarif -output "./out.sarif" $GITHUB_WORKSPACE${{ matrix.pom }}/target/*.jar
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: out.sarif