name: Code analysis
on: 
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A ${{ github.event_name }} event happened, starting workflow."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with: 
          languages: javascript, go
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - run: echo "Job ended."
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep scan --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/r
            p/security-audit
            p/secrets
            p/ci
            p/javascript
            p/scala
            p/go
            p/owasp-top-ten
            p/clientside-js
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
  # findsecbugs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   # TODO: this should run only once!
  #   - run: mvn package
  #   # TODO: how to change version of find-sec-bugs? How to set variables?
  #   - run: wget https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.12.0/findsecbugs-cli-1.12.0.zip
  #   - run: unzip findsecbugs-cli-1.12.0
  #   - run: chmod u+x ./findsecbugs.sh
  #   # TODO: how to make jar name more configurable
  #   - name: Run FindSecBugs checks
  #     run: ./findsecbugs.sh -sarif -output "./out.sarif" $GITHUB_WORKSPACE/target/states_source-0.1.jar
  #   - name: Upload SARIF file
  #     uses: github/codeql-action/upload-sarif@v2
  #     with:
  #       sarif_file: out.sarif