name: Code analysis
on: 
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A ${{ github.event_name }} event happened, starting workflow."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with: 
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - run: echo "Job ended."
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep scan --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/r
            p/security-audit
            p/secrets
            p/ci
            p/javascript
            p/owasp-top-ten
            p/clientside-js
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif